app-name: slab31
server:
 port: 8081
 servlet.context-path: /${app-name}

db:
 url: mysql-default
 username: root-default
 password: Aadi@123-default
 use-mysql: use-mysql-default

myserver:
 ip:
 - 1.1.1.1
 - 2.2.2.2
 - 3.3.3.3

testapp: hello1